/**
 * Yahoo Finance symbols supported by `/api/etf-chart` and `getCachedEtfChart`.
 * Keep in sync with hub listings that have on-site ETF pages.
 */
export const ETF_CHART_SYMBOLS = [
  'BEGS',
  'BTGD',
  'OOQB',
  'OOSB',
  'RSSX',
  'WTIB',
  'MATE',
  'RSBT',
  'RSST',
  'RSIT',
  'CTAP',
  'RSSY',
  'RSSB',
  'NTSD',
  'NTSX',
  'NTSI',
  'NTSE',
  'GDE',
  'GDMN',
  'WDIG',
  'GDT',
  'FLSP',
  'IALT',
  'CAOS',
  'ATTR',
  'SSO',
  'UPRO',
  'QLD',
  'TQQQ',
  'SPMO',
  'VFLO',
  'SASS',
  'AVUV',
  'AVDV',
  'COWZ',
  'PTF',
  'CTA',
  'DBMF',
  'KMLM',
  'MEMA',
  'CLSE',
  'VAMO',
  'MRGR',
  'HARD',
  'HOLD',
  'ORR',
  'ASGM',
  'HFGM',
  'HSU.TO',
  'HQU.TO',
  'USSL.TO',
  'QQQL.TO',
  'HEQL.TO',
  'RGBM.TO',
  'ONEC.TO',
  'PFAA.TO',
  'ZLB.TO',
  'FCMO.TO',
  'FCCM.TO',
  'PMM.TO',
  'ATSX.TO',
  'PFAE.TO',
  'HDGE.TO',
  'PFLS.TO',
  'PFMN.TO',
  'TGAF.TO',
  'DGLM.TO',
  'BTCC-B.TO',
  'ETHX-B.TO',
  'ARB.TO',
  'JAAA',
  'CLOA',
  'BAAA.TO',
  'SPBC',
  'FOXY',
  'WTLS',
] as const

export type EtfChartYahooSymbol = (typeof ETF_CHART_SYMBOLS)[number]

export function isAllowedEtfChartSymbol(s: string): s is EtfChartYahooSymbol {
  return (ETF_CHART_SYMBOLS as readonly string[]).includes(s.toUpperCase())
}
